using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Net;
using System.Xml;
using System.IO;

namespace ClientConsumingWebService
{

    /// <summary>
    /// Uses Soap protocol for message exchange on HTTP protocol layer.
    /// </summary>
    class SoapClient
    {
        public SoapClient()
        {
                
        }

        static void Main(string[] args)
        {
            // Address : http://localhost:4394/PSWebService.asmx
            SoapClient test = new SoapClient();
            test.InvokeService();
            //PSWebServiceSoapClient psClient = new PSWebServiceSoapClient();
            //var res = psClient.HelloWorld();
        }

        public HttpWebRequest CreateSoapWebRequest()
        {
            HttpWebRequest request = WebRequest.CreateHttp("http://localhost:4394/PSWebService.asmx");
            request.Headers.Add("SOAPAction: http://tempuri.org/HelloWorld");
            request.ContentType = "text/xml; charset=\"utf-8\"";
            //request.Accept = "text/xml";//try removing it
            request.Method = "POST";

            return request;
        }

        public void InvokeService()
        {
            HttpWebRequest request = this.CreateSoapWebRequest();
            XmlDocument soapRequest = new XmlDocument();
            //Sopa request generated by hitting asmx uri
            soapRequest.LoadXml(@"<?xml version=""1.0"" encoding=""utf-8""?><soap:Envelope xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:soap=""http://schemas.xmlsoap.org/soap/envelope/""><soap:Body><HelloWorld xmlns=""http://tempuri.org/"" /></soap:Body></soap:Envelope>");
            using (Stream stream = request.GetRequestStream())
            {
                soapRequest.Save(stream);
            } 

            using (WebResponse services = request.GetResponse())
            {
                using (StreamReader read = new StreamReader(services.GetResponseStream()))
                {
                    var result = read.ReadToEnd();
                    Console.Write(result);
                    Console.ReadKey();
                }
            }

        }
    }
}
